### PR TITLE
Fix bug when step's selector doesn't exist.

### PR DESCRIPTION
**Pull request by mattgrande**
I came across a situation where the Joyride was expecting an element to exist... but it didn't. What happened was the joyride just failed, and the screen stayed grey'd out.

This commit changes that behaviour to display the 'element' step as if it was a 'Regular' step.

### CODE REVIEW

**Review by ahmed-wagdi — CHANGES_REQUESTED** [review]
This is great, just 2 minor things that need to be changed:

1- Run Gulp compress so that these changes go into the js files in the /dist folder

2- If the selector is incorrect add a `console.warn()` to print a message in the console to let the developer know what went wrong. It's good that the directive doesn't break after this change but it's important to let the dev know that something went wrong.

Let me know if you'll be able to make these changes, if not i'll merge and update it when i'm free.

**Comment by mattgrande** [comment]
Yep, no problem. I'll get to them in a few hours.

**Comment by mattgrande** [comment]
I changed my mind and opted to do it now :) Let me know if you have any other comments/concerns.

**Review by ahmed-wagdi — APPROVED** [review]

**Comment by mattgrande** [comment]
Thanks for merging this! Are you planning on doing another release anytime soon?

**Comment by ahmed-wagdi** [comment]
No problem, i appreciate any help i can get :)

I published the changes you made to make sure people get the updated version.

**Pull request merged**
