### PR TITLE
The run function was not using strict dependency injection.

### PR DESCRIPTION
**Pull request by mattgrande**
This caused the `joyride.min.js` file to not work when in `strict-di` mode.

See here: https://docs.angularjs.org/error/$injector/strictdi

### CODE REVIEW

**Review by ahmed-wagdi — COMMENTED** [review]
Adding npm installation is definitely a good idea but why did you remove bower?

**Comment by mattgrande** [comment]
Woah, I didn't intend for those commits to end up here. I needed a strict DI version, so I released on NPM and, since the Bower version was now outdated, removed it from the readme.

**Comment by ahmed-wagdi** [comment]
could you please remove the npm package you created or atleast change it's name? I intend on publishing it on npm after the directive is completed which should be very soon.

**Comment by mattgrande** [comment]
Yeah, can do, but I'm using it in an existing project, so I've gotta make some changes to my codebase. Will switch it over tomorrow!

**Comment by ahmed-wagdi** [comment]
Ok great, thanks. Also if you have any feedback or suggestions please let me know.

**Comment by ahmed-wagdi** [comment]
@mattgrande i'm still waiting for you to remove that npm package. I would really appreciate it if you did this soon as the directive is now stable enough to release.

Thank you.

**Comment by mattgrande** [comment]
Sorry, @ahmed-wagdi, I forgot to get back to you.

NPM has made it a serious pain in the ass to unpublish things (see here: http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy)

What I'd like to do is make you the owner of the existing NPM package. I'd need you to get an NPM username for that though (I tried to add the user `ahmed-wagdi`, but that doesn't seem to exist).

Again, sorry for the confusion. I assumed you had stopped caring about/supporting this plugin.

**Comment by ahmed-wagdi** [comment]
@mattgrande it's fine and thank you for understanding. I just created an account, username is `ahmed-wagdi`.

**Comment by mattgrande** [comment]
Alright, you should be an owner on this one now as well!

**Edit:** Also, sorry it took so long, I was out of town all weekend.

**Pull request closed without merging**
